projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: "http://localhost:5000"
  database:
    schemaPath: src/generated/database.graphql
    extensions:
      prisma: database/prisma.yml
      binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
  